//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class kamar
    {
        public int id { get; set; }
        public int no_kamar { get; set; }
        public string nm_kamar { get; set; }
        public string tipe_kamar { get; set; }
        public Nullable<int> hrg { get; set; }
    }
}
