//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class pelanggan
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string nama_plg { get; set; }
        public string alamat { get; set; }
        public Nullable<System.DateTime> tgl_lahir { get; set; }
        public string no_telp { get; set; }
    }
}
